### Simulate Login Request
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Helvos",
  "password": "jajesamcarsveta2"
}

### Use the token obtained from login to access protected route
GET http://localhost:3000/test_protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmY5ZDBjNWQzYWI0ZTJiZjUwODI3YTYiLCJpYXQiOjE3Mjc2NDgxMTIsImV4cCI6MjA0MzIyNDExMn0.CIdTzwhkFiGUr467HBZvyIMfSPUfpFOwGNdrLz_NUks