### Token reference
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2FhMmE2NmU4MmE0NGQzMzk5MTg1NjQiLCJpYXQiOjE3NDEyNTI0MjcsImV4cCI6MjA1NjgyODQyN30.aLzmngMnfDYPUOUCcvLdR8MbUcYzCudXoHCThctjNGk

### Simulate Login Request
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "helvos",
  "password": "helvos"
}

#=#=#=#=#=#=[ CATEGORIES ]=#=#=#=#=#=#

### Category GET
GET http://localhost:3000/categories
Authorization: Bearer {{token}}

### Test adding new category
POST http://localhost:3000/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "category": {
    "name": "Torbica"
  }
}

### Test removing a category
DELETE http://localhost:3000/categories/67053218261eee01749028fc
Authorization: Bearer {{token}}
Content-Type: application/json
