### Token reference
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmZkYjA4YzM2N2QzZmYxOGRkZmM2YmYiLCJpYXQiOjE3MjgzODgyMzEsImV4cCI6MjA0Mzk2NDIzMX0.9_ylHmcm14Mpj5hbe1n2mLr0WjAvd3t6WaWbCl6i6Kk

### Simulate Login Request
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "helvos",
  "password": "helvos"
}

#=#=#=#=#=#=[ CATEGORIES ]=#=#=#=#=#=#

### Category GET
GET http://localhost:3000/categories
Authorization: Bearer {{token}}

### Test adding new category
POST http://localhost:3000/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "category": {
    "name": "Haljina"
  }
}

### Test removing a category
DELETE http://localhost:3000/categories/67051940d14291824de55370
Authorization: Bearer {{token}}
Content-Type: application/json
