### Token reference
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmZkYjA4YzM2N2QzZmYxOGRkZmM2YmYiLCJpYXQiOjE3MjgzODgyMzEsImV4cCI6MjA0Mzk2NDIzMX0.9_ylHmcm14Mpj5hbe1n2mLr0WjAvd3t6WaWbCl6i6Kk

### Simulate Login Request
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "helvos",
  "password": "helvos"
}

#=#=#=#=#=#=[ DRESSES ]=#=#=#=#=#=#

### Simulate getting all active dressses
GET http://localhost:3000/products/active-dresses
Authorization: Bearer {{token}}

### Simulate getting all inactive dressses
GET http://localhost:3000/products/inactive-dresses
Authorization: Bearer {{token}}

### Test removing an active dress
DELETE http://localhost:3000/products/dress/670aee4dac4692bbf6f17652
Authorization: Bearer {{token}}
Content-Type: application/json